pub(crate) mod one_chapter;
pub(crate) mod three_chapters;

#[derive(Eq, PartialEq, Debug, Clone, Copy)]
enum Halacha {
    TransmissionOfTheOralLaw,
    PositiveMitzvot,
    NegativeMitzvot,
    OverviewOfMishnehTorahContents,
    FoundationsOfTheTorah,
    HumanDispositions,
    TorahStudy,
    ForeignWorshipAndCustomsOfTheNations,
    Repentance,
    ReadingTheShema,
    PrayerAndThePriestlyBlessing,
    TefillinMezuzahAndTheTorahScroll,
    Fringes,
    Blessings,
    Circumcision,
    TheOrderOfPrayer,
    Sabbath,
    Eruvin,
    RestOnTheTenthOfTishrei,
    RestOnAHoliday,
    LeavenedAndUnleavenedBread,
    ShofarSukkahAndLulav,
    SheqelDues,
    SanctificationOfTheNewMonth,
    Fasts,
    ScrollOfEstherAndHanukkah,
    Marriage,
    Divorce,
    LevirateMarriageAndRelease,
    VirginMaiden,
    WomanSuspectedOfInfidelity,
    ForbiddenIntercourse,
    ForbiddenFoods,
    RitualSlaughter,
    Oaths,
    Vows,
    Nazariteship,
    AppraisalsAndDevotedProperty,
    DiverseSpecies,
    GiftsToThePoor,
    HeaveOfferings,
    Tithes,
    SecondTithesAndFourthYearsFruit,
    FirstFruitsAndOtherGiftsToPriestsOutsideTheSanctuary,
    SabbaticalYearAndTheJubilee,
    TheChosenTemple,
    VesselsOfTheSanctuaryAndThoseWhoServeTherein,
    AdmissionIntoTheSanctuary,
    ThingsForbiddenOnTheAltar,
    SacrificialProcedure,
    DailyOfferingsAndAdditionalOfferings,
    SacrificesRenderedUnfit,
    ServiceOnTheDayOfAtonement,
    Trespass,
    PaschalOffering,
    FestivalOffering,
    Firstlings,
    OfferingsForUnintentionalTransgressions,
    OfferingsForThoseWithIncompleteAtonement,
    Substitution,
    DefilementByACorpse,
    RedHeifer,
    DefilementByLeprosy,
    ThoseWhoDefileBedOrSeat,
    OtherSourcesOfDefilement,
    DefilementOfFoods,
    Vessels,
    ImmersionPools,
    DamagesToProperty,
    Theft,
    RobberyAndLostProperty,
    OneWhoInjuresAPersonOrProperty,
    MurdererAndThePreservationOfLife,
    Sales,
    OwnerlessPropertyAndGifts,
    Neighbors,
    AgentsAndPartners,
    Slaves,
    Hiring,
    BorrowingAndDeposit,
    CreditorAndDebtor,
    PlaintiffAndDefendant,
    Inheritances,
    TheSanhedrinAndThePenaltiesWithinTheirJurisdiction,
    Testimony,
    Rebels,
    Mourning,
    KingsAndWars,
}

const HALACHAS: [Halacha; 88] = {
    use Halacha::*;
    [
        TransmissionOfTheOralLaw,
        PositiveMitzvot,
        NegativeMitzvot,
        OverviewOfMishnehTorahContents,
        FoundationsOfTheTorah,
        HumanDispositions,
        TorahStudy,
        ForeignWorshipAndCustomsOfTheNations,
        Repentance,
        ReadingTheShema,
        PrayerAndThePriestlyBlessing,
        TefillinMezuzahAndTheTorahScroll,
        Fringes,
        Blessings,
        Circumcision,
        TheOrderOfPrayer,
        Sabbath,
        Eruvin,
        RestOnTheTenthOfTishrei,
        RestOnAHoliday,
        LeavenedAndUnleavenedBread,
        ShofarSukkahAndLulav,
        SheqelDues,
        SanctificationOfTheNewMonth,
        Fasts,
        ScrollOfEstherAndHanukkah,
        Marriage,
        Divorce,
        LevirateMarriageAndRelease,
        VirginMaiden,
        WomanSuspectedOfInfidelity,
        ForbiddenIntercourse,
        ForbiddenFoods,
        RitualSlaughter,
        Oaths,
        Vows,
        Nazariteship,
        AppraisalsAndDevotedProperty,
        DiverseSpecies,
        GiftsToThePoor,
        HeaveOfferings,
        Tithes,
        SecondTithesAndFourthYearsFruit,
        FirstFruitsAndOtherGiftsToPriestsOutsideTheSanctuary,
        SabbaticalYearAndTheJubilee,
        TheChosenTemple,
        VesselsOfTheSanctuaryAndThoseWhoServeTherein,
        AdmissionIntoTheSanctuary,
        ThingsForbiddenOnTheAltar,
        SacrificialProcedure,
        DailyOfferingsAndAdditionalOfferings,
        SacrificesRenderedUnfit,
        ServiceOnTheDayOfAtonement,
        Trespass,
        PaschalOffering,
        FestivalOffering,
        Firstlings,
        OfferingsForUnintentionalTransgressions,
        OfferingsForThoseWithIncompleteAtonement,
        Substitution,
        DefilementByACorpse,
        RedHeifer,
        DefilementByLeprosy,
        ThoseWhoDefileBedOrSeat,
        OtherSourcesOfDefilement,
        DefilementOfFoods,
        Vessels,
        ImmersionPools,
        DamagesToProperty,
        Theft,
        RobberyAndLostProperty,
        OneWhoInjuresAPersonOrProperty,
        MurdererAndThePreservationOfLife,
        Sales,
        OwnerlessPropertyAndGifts,
        Neighbors,
        AgentsAndPartners,
        Slaves,
        Hiring,
        BorrowingAndDeposit,
        CreditorAndDebtor,
        PlaintiffAndDefendant,
        Inheritances,
        TheSanhedrinAndThePenaltiesWithinTheirJurisdiction,
        Testimony,
        Rebels,
        Mourning,
        KingsAndWars,
    ]
};

fn max_halacha(halacha: Halacha) -> u8 {
    match halacha {
        Halacha::TransmissionOfTheOralLaw => 3,
        Halacha::PositiveMitzvot => 3,
        Halacha::NegativeMitzvot => 3,
        Halacha::OverviewOfMishnehTorahContents => 3,
        Halacha::FoundationsOfTheTorah => 10,
        Halacha::HumanDispositions => 7,
        Halacha::TorahStudy => 7,
        Halacha::ForeignWorshipAndCustomsOfTheNations => 12,
        Halacha::Repentance => 10,
        Halacha::ReadingTheShema => 4,
        Halacha::PrayerAndThePriestlyBlessing => 15,
        Halacha::TefillinMezuzahAndTheTorahScroll => 10,
        Halacha::Fringes => 3,
        Halacha::Blessings => 11,
        Halacha::Circumcision => 3,
        Halacha::TheOrderOfPrayer => 4,
        Halacha::Sabbath => 30,
        Halacha::Eruvin => 8,
        Halacha::RestOnTheTenthOfTishrei => 3,
        Halacha::RestOnAHoliday => 8,
        Halacha::LeavenedAndUnleavenedBread => 9,
        Halacha::ShofarSukkahAndLulav => 8,
        Halacha::SheqelDues => 4,
        Halacha::SanctificationOfTheNewMonth => 19,
        Halacha::Fasts => 5,
        Halacha::ScrollOfEstherAndHanukkah => 4,
        Halacha::Marriage => 25,
        Halacha::Divorce => 13,
        Halacha::LevirateMarriageAndRelease => 8,
        Halacha::VirginMaiden => 3,
        Halacha::WomanSuspectedOfInfidelity => 4,
        Halacha::ForbiddenIntercourse => 22,
        Halacha::ForbiddenFoods => 17,
        Halacha::RitualSlaughter => 14,
        Halacha::Oaths => 12,
        Halacha::Vows => 13,
        Halacha::Nazariteship => 10,
        Halacha::AppraisalsAndDevotedProperty => 8,
        Halacha::DiverseSpecies => 10,
        Halacha::GiftsToThePoor => 10,
        Halacha::HeaveOfferings => 15,
        Halacha::Tithes => 14,
        Halacha::SecondTithesAndFourthYearsFruit => 11,
        Halacha::FirstFruitsAndOtherGiftsToPriestsOutsideTheSanctuary => 12,
        Halacha::SabbaticalYearAndTheJubilee => 13,
        Halacha::TheChosenTemple => 8,
        Halacha::VesselsOfTheSanctuaryAndThoseWhoServeTherein => 10,
        Halacha::AdmissionIntoTheSanctuary => 9,
        Halacha::ThingsForbiddenOnTheAltar => 7,
        Halacha::SacrificialProcedure => 19,
        Halacha::DailyOfferingsAndAdditionalOfferings => 10,
        Halacha::SacrificesRenderedUnfit => 19,
        Halacha::ServiceOnTheDayOfAtonement => 5,
        Halacha::Trespass => 8,
        Halacha::PaschalOffering => 10,
        Halacha::FestivalOffering => 3,
        Halacha::Firstlings => 8,
        Halacha::OfferingsForUnintentionalTransgressions => 15,
        Halacha::OfferingsForThoseWithIncompleteAtonement => 5,
        Halacha::Substitution => 4,
        Halacha::DefilementByACorpse => 25,
        Halacha::RedHeifer => 15,
        Halacha::DefilementByLeprosy => 16,
        Halacha::ThoseWhoDefileBedOrSeat => 13,
        Halacha::OtherSourcesOfDefilement => 20,
        Halacha::DefilementOfFoods => 16,
        Halacha::Vessels => 28,
        Halacha::ImmersionPools => 11,
        Halacha::DamagesToProperty => 14,
        Halacha::Theft => 9,
        Halacha::RobberyAndLostProperty => 18,
        Halacha::OneWhoInjuresAPersonOrProperty => 8,
        Halacha::MurdererAndThePreservationOfLife => 13,
        Halacha::Sales => 30,
        Halacha::OwnerlessPropertyAndGifts => 12,
        Halacha::Neighbors => 14,
        Halacha::AgentsAndPartners => 10,
        Halacha::Slaves => 9,
        Halacha::Hiring => 13,
        Halacha::BorrowingAndDeposit => 8,
        Halacha::CreditorAndDebtor => 27,
        Halacha::PlaintiffAndDefendant => 16,
        Halacha::Inheritances => 11,
        Halacha::TheSanhedrinAndThePenaltiesWithinTheirJurisdiction => 26,
        Halacha::Testimony => 22,
        Halacha::Rebels => 7,
        Halacha::Mourning => 14,
        Halacha::KingsAndWars => 12,
    }
}
